### ISSUE TITLE
Relationship of digital object to catkey

### ISSUE THREAD

**Issue by arcadiafalcone** [sul-dlss-labs/sdr3-models#2]
https://github.com/sul-dlss-labs/sdr3-models/blob/3e6d644123ece0850c3fb8d7a6793e4dbc3f0aec/taco-maps/DRO.json#L156

The bibliographic record designated by the catkey often describes the physical object for which the digital object is the surrogate, not the same digital object.

In local practice the MODS metadata also mostly describes the physical object when the digital object is considered a surrogate (there are a few technical metadata fields under physicalDescription that describe the digital file, but extent, date created, form, etc. all describe the physical object).

**Comment by cmh2166** [comment]
Yep, that’s why there are ‘catkey’, ‘sameAs’, ‘sourceId’, and ‘isRepresentationOf’ fields available. I believe that covers all possible relationships between surrogates etc. Do you have requested changes or questions, info, etc on this identifier & representation matrix so far? Thanks!
		
		

		Get Outlook for iOS
	




On Tue, Mar 13, 2018 at 8:54 AM -0700, "arcadiafalcone" <notifications@github.com> wrote:












https://github.com/sul-dlss-labs/sdr3-models/blob/3e6d644123ece0850c3fb8d7a6793e4dbc3f0aec/taco-maps/DRO.json#L156


The bibliographic record designated by the catkey often describes the physical object for which the digital object is the surrogate, not the same digital object.


In local practice the MODS metadata also mostly describes the physical object when the digital object is considered a surrogate (there are a few technical metadata fields under physicalDescription that describe the digital file, but extent, date created, form, etc. all describe the physical object).

**Comment by arcadiafalcone** [comment]
In writing the below I realized eventually that I was thinking ahead to functionality beyond TACO that does not need to be supported in this model (though please tell me if I'm wrong), so consider it as context for future work. The actionable bit is really only that I think the catkey description in the model should be clearer on the scope and nature of its relationship to the digital object, so I'll take a stab at that and submit a pull request.
--
Thinking functionally, the catkey operates on the digital object in three distinct ways:
1. It identifies the bibliographic record that serves as the metadata source for the digital object metadata in DOR and purl (=input for Argo "refresh from source" process).
2. It defines the SearchWorks URL at which the digital object may be accessed (=target for Stanford Sync process).
3. It indicates that the digital object represents all or part of the same Work as is described by the record at the catkey.

So the functional relationships are more like hasMetadataSource, hasAccessPoint, and alsoDescribedBy. The "catkey" attribute as it is currently defined in the data model covers the alsoDescribedBy relationship (if "digital" is dropped from the definition).

Decoupling these three relationships from each other would also solve an issue we've run into where we want the hasAccessPoint and alsoDescribedBy relationships, but not the hasMetadataSource one.

(To be even more specific, hasMetadataSource has three distinct functional contexts: a) the digital object metadata should be automatically regenerated any time the source changes; b) the digital object metadata was initially derived from the source and may be manually regenerated, but the sync is not automatically maintained; c) the digital object metadata was initially derived from the source, but cannot be overwritten by it. Currently only (b) is supported.)
